"""
Django settings for bigdataflow project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&b%ab=q)!8d7p-!$v^*4+wf*m%c+nu@%o9j_=dg=u5i5krf7uh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor_uploader',
    'crispy_forms',
    'adminlte',
    'workflow',
    'rest_framework',
    # 'guardian',
    # 'users.apps.UsersConfig',
]

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend', # django默认的backend
#     'guardian.backends.ObjectPermissionBackend',
# )

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [

    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bigdataflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bigdataflow.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# 使用mysql数据库
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'bigdataflow',  # Or path to database file if using sqlite3.
        'USER': 'root',  # Not used with sqlite3.
        'PASSWORD': '123456',  # Not used with sqlite3.
        'HOST': '127.0.0.1',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '3306',  # Set to empty string for default. Not used with sqlite3.
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# 创建静态文件路径
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
if not os.path.exists(MEDIA_ROOT):
    os.mkdir(MEDIA_ROOT, mode=511)

# crispy在setting中的配置  by kf
CRISPY_TEMPLATE_PACK = 'bootstrap3'
#
# 使用django ckeditor库文件，CHEDITOR_UPLOAD_PATH的作用是设定你通过ckeditor所上传的文件的存放目录  by kf
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        # 'height': 300,
        'width': '100%',
    },
}
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_USER = True
IMAGE_QUALITY = 40
THUMBNAIL_SIZE = (300, 300)

CSRF_COOKIE_NAME = 'bigdataflow'
SESSION_COOKIE_NAME = 'bigdataflowsession'

LOGIN_REDIRECT_URL = '/'

# 以下为loonflow后端地址及在loonflow中配置的授权应用及token. 初始化sql中是此记录，如果有在loonflow中修改，此处也需要相应修改
# WORKFLOWBACKENDURL = "http://39.106.36.234:6060"
# WORKFLOWTOKEN = "dc84bc8c-9c9d-11ea-b6f0-a3680e98fe31"
# WORKFLOWAPPNAME = "bigdataflow"

WORKFLOWBACKENDURL = "http://39.106.36.234:7090"
WORKFLOWTOKEN = "3c6e4bf8-b3ce-11ea-98f0-a3680e98fe31"
WORKFLOWAPPNAME = "110"

WORKTEMPSAVEBUTTONNAME = "提交施工进度数据"
FLOWINPUTSTR = "j_shigongjindu_float_zonghengzumaosuo,j_shigongjindu_float_muqianhengzumaosuo,j_shigongjindu_float_zongqiefengzhuankong,j_shigongjindu_float_muqianqiefengzhuankong,j_shigongjindu_float_zongbaopoliefeng,j_shigongjindu_float_muqianbaopoliefeng"

NEWPRO = "auth.newpro"
MYPRO = "auth.mypro"
MYTODO = "auth.mytodo"
MYRELA = "auth.myrela"
ALL = "auth.all"

# 用户信息添加手机号码字段
# AUTH_USER_MODEL= 'workflow.User'

EMAIL_HOST = 'smtp.qq.com'
EMAIL_FROM = '923683429@qq.com'
EMAIL_HOST_PASSWORD = 'kuectoixnwvdbcbf'
EMAIL_PORT = 465

EMAIL_FROM_TITLE = "大数据工法管理系统<http://127.0.0.1:8080/>"
